language: ruby
sudo: false
cache: bundler
dist: trusty
addons:
  apt:
    packages:
      - haveged
# NOTE: these run in order
rvm:
  - jruby
  - rbx-3.73
  - 2.2.7
  - 2.3.4
  - 2.4.1
matrix:
  allow_failures:
    - rvm: rbx-3.73
    - rvm: jruby
